### ISSUE TITLE
Some thing is not right

### ISSUE THREAD

**Issue by mrbubble62** [ttlappalainen/NMEA2000_esp32#1]
ESP32 is adding extra data to the begining of each message.
ArduinoGateway Teensy and ESP32 do not show the same results.  NMEA Reader cannot display ESP32 packets.

The following packets were captured simultaneously with ArduinoGateway in ASCII mode.
ESP32
2089326 : Pri:7 PGN:127258 Source:8 Dest:255 Len:8 Data:FF,FF,FF,FF,91,F8,FF,FF<\r><\n>
2089327 : Pri:3 PGN:130845 Source:8 Dest:255 Len:8 Data:40,E,41,9F,FF,FF,FF,FF<\r><\n>
2089329 : Pri:3 PGN:130845 Source:8 Dest:255 Len:8 Data:41,2,0,0,1,91,F8,0<\r><\n>
2089335 : Pri:3 PGN:130845 Source:8 Dest:255 Len:8 Data:42,0,FF,FF,FF,FF,FF,FF<\r><\n>
2090341 : Pri:7 PGN:127258 Source:8 Dest:255 Len:8 Data:FF,FF,FF,FF,91,F8,FF,FF<\r><\n>

Teensy
789311 : Pri:7 PGN:127258 Source:8 Dest:255 Len:8 Data:FF,FF,FF,FF,91,F8,FF,FF<\r><\n>
789312 : Pri:3 PGN:130845 Source:8 Dest:255 Len:8 Data:40,E,41,9F,FF,FF,FF,FF<\r><\n>
789312 : Pri:3 PGN:130845 Source:8 Dest:255 Len:8 Data:41,2,0,0,1,91,F8,0<\r><\n>
789313 : Pri:3 PGN:130845 Source:8 Dest:255 Len:8 Data:42,0,FF,FF,FF,FF,FF,FF<\r><\n>
790326 : Pri:7 PGN:127258 Source:8 Dest:255 Len:8 Data:FF,FF,FF,FF,91,F8,FF,FF<\r><\n>

**Comment by ttlappalainen** [comment]
Could you explain more precicely? I just tested ActisenseListener and it worked fine and NMEA Reader showed messages as with other systems. The only difference on text mode I could see is the time stamp on the beginning. take care that you do not have call: `NMEA2000.SetForwardType(tNMEA2000::fwdt_Text);` on your code, if you use Actisense NMEA reader. It requires its own format.

**Comment by mrbubble62** [comment]
Yes I started with Actisense mode and with GPS and MFD traffic it crashed NMEA Reader. That's when I began debug but every CRC was wrong, so I recompiled with tNMEA2000::fwdt_Text then I saw the time stamps are different but the samples were captured at the _exact_ same time using both boards and a very slow message rate on the N2K network.  I have many working devices around here now thanks to you and they have never shown this issue.

**Comment by ttlappalainen** [comment]
Note that timestamps are not any bus time stamps. They are just times since your program started on your device. On ESP32 WiFi setup takes more time so it will allways show higher timestamps.

I have also had problems with  NMEA Reader 1.5 crashing. Just restart and it worked fine. The newer release seem to be more stable.

As on your list data itself is right. So once again I ask you to check bus terminating.  I have about 11 devices on my table and switching between them. Time to time I have strange behaviour, when I forgot set terminating right. Dues to changes I may have 0-4 terminating resistors and only 2 is 100% sure, 1 for short distances.

I have NMEA2000 -> WiFi NMEA0183 converter sample coming.

**Comment by ttlappalainen** [comment]
I just realised that have you tested with ActisenseListener? ActisenseGateway also reads data from Serial. I have not tested does read do some blocking on ESP32.
